### ISSUE TITLE
Glitches for NWN 6/18/20 (Trevor)

### ISSUE THREAD

**Issue by TrevorSTroxel** [rpgresearch/erpg#2]
- P1F4Module
-No issues as of 6/18/20
- P1_F7_animal
-When freeing the dog, it does not run off. It stays in place: When choosing the option to free the dog, the dialogue states that it is free and runs away but it remains in place.
-Both door transition does not work: Both doors on the map do not work. this may be due to areas not being the same module.
-Choosing any option, besides killing the dog, does not do anything as you are allowed to talk the dog again, as it stays there and does nothing. Unknown if this feature is unfinished or not.
-Game will randomly crash for unknown reasons: Playing for an extended period of time the game will cash without any warning.
- P1E7GRID
-Door transitions do not work: Doors on the map do not work. This may be due to areas not being the same module.
-Games crashes for no random reason: Playing for an extended period of time the game will cash without any warning.
- P1E8ENTER
-Door transitions do not work: Doors on the map do not work. This may be due to areas not being the same module.
 -Games crashes for no random reason: Playing for an extended period of time the game will cash without any warning.
- P1H5MODULE
- No issues as of 6/18/20
- P1F6CALIBAN
-Doors does not have transition into anything
-Every time you talk to Caliban, he acts like he has never seen you before
- P1E9FIGURE
-Doors do not transition to anything
-Arial disappears and reapers when at a certain distance. 
- B10-11ModuleFinal
•	King Alfonso dialogue is incomplete, after asking him what he knows about Prospero, the dialogue ends.
•	A chest of equipment is in a chest in a jail cell? Unknown if this was intentional and meant to be looted by players or if was meant to be taken out and has not yet.
•	A chest in a room with a heart shape pool in it? Unknown if this was intentional and meant to be looted by players or if was meant to be taken out and has not yet.
•	No mirrors in the room with a heart shaped pool work.
•	The Odd Journal is unreadable? Unknown if this is meant to be readable to players or if it only used to open up new dialogue options with the King
•	The key and Odd journal can be found laying in the starting rooms by the players. Unknow if this is intentional or These items are meant to appear in random places.
•	King Alonso and Kantana can die
- P1D10
•	No issues so far

**Comment by tnoye** [comment]
## P1F4Module
- ~Crashes if idle too long: Playing for an extended period of time the game will cash without any warning.~
    - Not certain if this is a level creation bug or related to the actual game.
- ~Stephano will head back to camp even if not instructed: When talking to Stephano, if you say nothing he will head straight back to camp without being told to do so.~
    - This has been corrected
- ~Games crashes when going through loading zones: Sometimes the game will crash when going through loading screens too fast.~
    - There are some waypoints and area triggers that aren't properly set up due to us not completely combining modules.
- ~NWN logo will sometimes appears on screen for no given reason: For no reason the NWN logo will randomly appear on the screen for a quarter of a second. Unable to capture this as it happens to fast.~
    - I believe this occurs when the server saves the current progress, I don't believe this is due to any level creation.


## P1H5MODULE
- ~Crab is beetle?: when looking around on the map there is a neutral creature labeled as crab, but is clearly a beetle. Unknown if this was done on purpose or due to a glitch.~
    - Beetle model is used in place of a crab as there is no existing crab model within the aurora toolset.

**Comment by zakbarba** [comment]
P1_F7_animal

-When freeing the dog, it does not run off. It stays in place: When choosing the option to free the dog, the dialogue states that it is free and runs away but it remains in place. (WIP)
-Both door transition does not work: Both doors on the map do not work. this may be due to areas not being the same module. (Not connected to anything)
-You are able to kill the dog before talking to it, it attacks despite being tied up in rope: though the dialogue says otherwise, the dog will attack PC if they choose to fight it, despite being tied up and in a weak state. (Fixed)
-Choosing any option, besides killing the dog, does not do anything as you are allowed to talk the dog again, as it stays there and does nothing. Unknown if this feature is unfinished or not.
-Game will randomly crash for unknown reasons: Playing for an extended period of time the game will cash without any warning.

-P1E7GRID
(I believe this grid is just a placeholder and not intended for anything other than scenery atm)
-Door transitions do not work: Doors on the map do not work. This may be due to areas not being the same module.
-Games crashes for no random reason: Playing for an extended period of time the game will cash without any warning.

P1E8ENTER
(I believe this grid is just a placeholder and not intended for anything other than scenery atm)
-Door transitions do not work: Doors on the map do not work. This may be due to areas not being the same module.
-Games crashes for no random reason: Playing for an extended period of time the game will cash without any warning.

P1F6CALIBAN

-Doors does not have transition into anything (Not connected to anything)
-Caliban is killable (Fixed)
-Every time you talk to Caliban, he acts like he has never seen you before (WIP)

P1E9FIGURE

-Doors do not transition to anything (Not connected to anything)
-Arial disappears and reapers when at a certain distance. ( This is intended as she is supposed to be tailing you)
